attributes:
  san_ip:
    value: ''
    label: 'IP'
    description: 'The IP address of the Dell EqualLogic array.'
    weight: 10
    type: "text"
  san_login:
    value: ''
    label: 'Username'
    description: 'The account to use for issuing SSH commands.'
    weight: 20
    type: "text"
  san_password:
    value: ''
    label: 'Password'
    description: 'The password for the specified SSH account.'
    weight: 30
    type: "password"
  eqlx_group_name:
    value: ''
    label: 'Volume Group Name'
    description: 'Volume GroupName, The CLI prompt message without >.'
    weight: 40
    type: "text"
  eqlx_pool:
    value: ''
    label: 'Pool Name'
    description: 'The pool in which volumes will be created.'
    weight: 50
    type: "text"
